### ISSUE TITLE
try to compile by myself

### ISSUE THREAD

**Issue by thefrogline** [Dominick12EU/LevelZone#1]
hi, i downloaded the src as i want to put particles when being driven by the zone, but when compiling it and putting it in my plugins folder i get this error: 

[00:02:15 ERROR] [Minecraft]: Could not load 'plugins\LevelZone-1.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: me/mattstudios/mf/base/CommandBase
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoaderMixin.java:149) ~[arclight-1.18.2-1.0.8-e80a33d2.jar%2369!/:arclight-1.18.2-1.0.8-e80a33d2]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[arclight-1.18.2-1.0.8-e80a33d2.jar%2369!/:arclight-1.18.2-1.0.8-e80a33d2]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[arclight-1.18.2-1.0.8-e80a33d2.jar%2369!/:arclight-1.18.2-1.0.8-e80a33d2]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServerMixin.java:407) ~[arclight-1.18.2-1.0.8-e80a33d2.jar%2369!/:arclight-1.18.2-1.0.8-e80a33d2]
        at net.minecraft.server.dedicated.DedicatedServer.handler$zbm000$arclight$loadPlugins(DedicatedServerMixin.java:694) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:167) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2099) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%2373!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: me/mattstudios/mf/base/CommandBase

First I had compiled it with my changes and I had this error, but then I deleted the entire project and compiled it as is, and I kept having the same error, I don't know if you forgot to upload a local library or something like that (sorry my bad english)

**Comment by Dominick12EU** [comment]
you have to compile it as shadow jar

Il giorno mar 9 mag 2023 alle ore 11:12 SrFrogline ***@***.***>
ha scritto:

**Comment by thefrogline** [comment]
brilliant! it works thank you very much, I always use maven and it was weird to use gradle to me and I didn't know what that was, thank you very much, it would be very cool if you could modify how much the player is pushed through the wall, It's just an idea, thanks a lot for the help!
